name: Generate Snake

on:
  schedule:
    # a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: DgDevHub
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          # esse é o branch onde a imagem será salva
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
